@startuml

class User {
    -name: string
    -login: string
    -password: string
    -email: string
}

class Event {
    -name: string
    -pictureUrl: string
    -description: string
    -startDate: timestamp
    -endDate: timestamp
}

class Team {
    -name: string
    -captain: User
    -pictureUrl: string
}

class Task {
    -name: string
    -description: string
    -weight: number
    -flag: string
    -pictureUrl: string
}

class Solution {
    date: timestamp
}

class Hint {
    -content: string
}

class Sponsor {
    -pictureUrl: string
    -url: string
}

enum Role {
    ADMIN
    USER
    ORGANIZER
}


User -* Event
User -* Team
User -- Role
Event -- Sponsor
Task -down* Event
Task -* Hint
Task -* Solution


@enduml
