version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:11.1.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-frontend-{{ checksum "package.json" }}-{{checksum "package-lock.json"}}
          - v1-dependencies-frontend-{{ checksum "package.json" }}-
          - v1-dependencies-frontend-

      - run:
          name: NPM install for frontend module
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-frontend-{{ checksum "package.json" }}-{{checksum "package-lock.json"}}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - master