export const TRY_FETCH_EVENTS = "TRY_FETCH_EVENTS"
export const FETCH_EVENTS_SUCCEEDED = "FETCH_EVENTS_SUCCEEDED"
export const FETCH_EVENTS_FAILED = "FETCH_EVENTS_FAILED"

export const OPEN_EVENT = "OPEN_EVENT"
