export const TRY_LOGIN = "TRY_LOGIN"
export const SUCCESSFUL_LOGIN = "SUCCESSFUL_LOGIN"
export const FAILED_LOGIN = "FAILED_LOGIN"

export const TRY_FETCH_EVENTS = "TRY_FETCH_EVENTS"
export const FETCH_EVENTS_SUCCEEDED = "FETCH_EVENTS_SUCCEEDED"
export const FETCH_EVENTS_FAILED = "FETCH_EVENTS_FAILED"

export const TRY_REGISTRATION = "TRY_REGISTRATION"
export const SUCCESSFULL_REGISTRATION = "SUCCESSFUL_REGISTRATION"
export const FAILED_REGISTRATION = "FAILED_REGISTRATION"
